### ISSUE TITLE
main.py (Guess the number) gives error

### ISSUE THREAD

**Issue by RounakSarak** [RounakSarak/GameVerse#6]
It gives error when enter is given as input

**Comment by SnappingComet28** [comment]
please share a snippet of the error

**Comment by RounakSarak** [comment]
I cant send it now but I will for sure

**Comment by SnappingComet28** [comment]
is it this:
Traceback (most recent call last):
  File "g:\python\GameVerse\Guess The Number\main.py", line 13, in <module>   
    userNum = int(input("I guess the number is : "))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by RounakSarak** [comment]
Yes
